# ==================
# General Layout
# ==================

# Output:
#    command to produce output

# tester2.txt: tester.txt
# 	cat tester.txt > tester2.txt

# tester.txt:
# 	echo "this is a test" > tester.txt
CFLAGS=-Wall -g

all: ex1

clean:
	rm -f ex1